"""Tests for admin catalog API extensions: variants, images, banners."""
from __future__ import annotations

import io

import pytest
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from django.urls import reverse
from PIL import Image
from rest_framework import status
from rest_framework.test import APIClient


def _make_jpeg_bytes(width: int = 10, height: int = 10) -> bytes:
    """Return the bytes of a minimal valid JPEG image generated by Pillow."""
    buf = io.BytesIO()
    Image.new("RGB", (width, height), color=(200, 100, 50)).save(buf, format="JPEG")
    return buf.getvalue()

from apps.catalog.models import Banner, ProductImage, ProductVariant
from apps.catalog.tests.factories import (
    AttributeValueFactory,
    ProductFactory,
    ProductVariantFactory,
)

User = get_user_model()

@pytest.fixture
def api_client():
    return APIClient()


@pytest.fixture
def staff_user(db):
    return User.objects.create_user(
        email="staff@example.com",
        password="pass",
        is_staff=True,
    )


@pytest.fixture
def regular_user(db):
    return User.objects.create_user(
        email="regular@example.com",
        password="pass",
        is_staff=False,
    )


@pytest.fixture
def staff_client(api_client, staff_user):
    api_client.force_authenticate(user=staff_user)
    return api_client


@pytest.fixture
def regular_client(api_client, regular_user):
    api_client.force_authenticate(user=regular_user)
    return api_client


# ── Product Variant Tests ──────────────────────────────────────────────────────


@pytest.mark.django_db
class TestAdminProductVariantListView:
    def test_list_variants_staff_only(self, staff_client):
        product = ProductFactory(slug="test-prod")
        ProductVariantFactory(product=product, sku="V-001")
        ProductVariantFactory(product=product, sku="V-002")
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "test-prod"})
        response = staff_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        # ProductFactory triggers a signal that auto-creates one default variant,
        # so 2 explicit variants + 1 auto-created default = 3 total.
        assert response.data["count"] == 3

    def test_list_variants_forbidden_for_regular_user(self, regular_client):
        product = ProductFactory(slug="test-prod2")
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "test-prod2"})
        response = regular_client.get(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN

    def test_list_variants_forbidden_for_anonymous(self, api_client):
        product = ProductFactory(slug="test-prod-anon")
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "test-prod-anon"})
        response = api_client.get(url)
        # DRF returns 401 for unauthenticated requests, not 403
        assert response.status_code == status.HTTP_401_UNAUTHORIZED

    def test_create_variant(self, staff_client):
        product = ProductFactory(slug="create-prod")
        av = AttributeValueFactory()
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "create-prod"})
        payload = {
            "sku": "NEW-VAR-001",
            "is_active": True,
            "attribute_values": [av.pk],
        }
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_201_CREATED
        assert ProductVariant.objects.filter(sku="NEW-VAR-001", product=product).exists()

    def test_create_variant_invalid_sku_duplicate_case_insensitive(self, staff_client):
        product = ProductFactory(slug="dup-prod")
        ProductVariantFactory(product=product, sku="DUP-SKU")
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "dup-prod"})
        payload = {"sku": "dup-sku", "is_active": True, "attribute_values": []}
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_create_variant_invalid_price_override(self, staff_client):
        product = ProductFactory(slug="price-prod")
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "price-prod"})
        payload = {"sku": "PRICE-VAR-001", "price_override": "-1.00", "is_active": True, "attribute_values": []}
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_create_variant_404_for_nonexistent_product(self, staff_client):
        url = reverse("catalog:admin-product-variant-list", kwargs={"product_slug": "no-such-product"})
        payload = {"sku": "ORPHAN-VAR", "is_active": True, "attribute_values": []}
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_404_NOT_FOUND


@pytest.mark.django_db
class TestAdminProductVariantDetailView:
    def test_retrieve_variant(self, staff_client):
        product = ProductFactory(slug="ret-prod")
        variant = ProductVariantFactory(product=product, sku="RET-VAR")
        url = reverse(
            "catalog:admin-product-variant-detail",
            kwargs={"product_slug": "ret-prod", "pk": variant.pk},
        )
        response = staff_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        assert response.data["sku"] == "RET-VAR"

    def test_update_variant(self, staff_client):
        product = ProductFactory(slug="upd-prod")
        variant = ProductVariantFactory(product=product, sku="UPD-VAR-ORIG")
        url = reverse(
            "catalog:admin-product-variant-detail",
            kwargs={"product_slug": "upd-prod", "pk": variant.pk},
        )
        response = staff_client.patch(url, {"sku": "UPD-VAR-NEW", "attribute_values": []}, format="json")
        assert response.status_code == status.HTTP_200_OK
        variant.refresh_from_db()
        assert variant.sku == "UPD-VAR-NEW"

    def test_update_sku_uniqueness_excludes_self(self, staff_client):
        """Updating a variant's SKU to its own current value should succeed."""
        product = ProductFactory(slug="self-sku-prod")
        variant = ProductVariantFactory(product=product, sku="SELF-SKU")
        url = reverse(
            "catalog:admin-product-variant-detail",
            kwargs={"product_slug": "self-sku-prod", "pk": variant.pk},
        )
        response = staff_client.patch(url, {"sku": "SELF-SKU", "attribute_values": []}, format="json")
        assert response.status_code == status.HTTP_200_OK

    def test_update_sku_conflict_with_other_variant(self, staff_client):
        product = ProductFactory(slug="conflict-prod")
        ProductVariantFactory(product=product, sku="TAKEN-SKU")
        variant = ProductVariantFactory(product=product, sku="OTHER-SKU")
        url = reverse(
            "catalog:admin-product-variant-detail",
            kwargs={"product_slug": "conflict-prod", "pk": variant.pk},
        )
        response = staff_client.patch(url, {"sku": "taken-sku", "attribute_values": []}, format="json")
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_delete_variant(self, staff_client):
        product = ProductFactory(slug="del-prod")
        variant = ProductVariantFactory(product=product, sku="DEL-VAR")
        url = reverse(
            "catalog:admin-product-variant-detail",
            kwargs={"product_slug": "del-prod", "pk": variant.pk},
        )
        response = staff_client.delete(url)
        assert response.status_code == status.HTTP_204_NO_CONTENT
        assert not ProductVariant.objects.filter(pk=variant.pk).exists()

    def test_delete_variant_forbidden_for_regular_user(self, regular_client):
        product = ProductFactory(slug="forbid-del-prod")
        variant = ProductVariantFactory(product=product, sku="FORBID-VAR")
        url = reverse(
            "catalog:admin-product-variant-detail",
            kwargs={"product_slug": "forbid-del-prod", "pk": variant.pk},
        )
        response = regular_client.delete(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN


# ── Product Image Tests ────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestAdminProductImageListView:
    def test_list_images_staff(self, staff_client):
        product = ProductFactory(slug="img-list-prod")
        ProductImage.objects.create(product=product, external_url="https://example.com/1.jpg", alt_text="a")
        ProductImage.objects.create(product=product, external_url="https://example.com/2.jpg", alt_text="b")
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "img-list-prod"})
        response = staff_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        assert response.data["count"] == 2

    def test_upload_image_with_external_url(self, staff_client):
        product = ProductFactory(slug="ext-url-prod")
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "ext-url-prod"})
        payload = {
            "external_url": "https://example.com/img.jpg",
            "alt_text": "Test",
            "display_order": 0,
            "is_primary": False,
        }
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_201_CREATED
        assert ProductImage.objects.filter(product=product, external_url="https://example.com/img.jpg").exists()

    def test_upload_image_sets_primary_unsets_others(self, staff_client):
        product = ProductFactory(slug="primary-prod")
        existing = ProductImage.objects.create(
            product=product, external_url="https://example.com/old.jpg", is_primary=True
        )
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "primary-prod"})
        payload = {
            "external_url": "https://example.com/new.jpg",
            "alt_text": "New primary",
            "display_order": 1,
            "is_primary": True,
        }
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_201_CREATED
        existing.refresh_from_db()
        assert not existing.is_primary

    def test_upload_image_no_image_or_url_fails(self, staff_client):
        product = ProductFactory(slug="no-img-prod")
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "no-img-prod"})
        payload = {"alt_text": "Missing", "display_order": 0, "is_primary": False}
        response = staff_client.post(url, payload, format="json")
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_upload_image_invalid_type(self, staff_client):
        product = ProductFactory(slug="bad-type-prod")
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "bad-type-prod"})
        bad_file = SimpleUploadedFile("file.gif", b"GIF89a", content_type="image/gif")
        response = staff_client.post(
            url,
            {"image": bad_file, "alt_text": "GIF", "display_order": 0, "is_primary": False},
            format="multipart",
        )
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_upload_image_size_exceeded(self, staff_client):
        product = ProductFactory(slug="big-img-prod")
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "big-img-prod"})
        big_file = SimpleUploadedFile(
            "big.jpg",
            b"\xff\xd8\xff\xe0" + b"\x00" * (6 * 1024 * 1024),
            content_type="image/jpeg",
        )
        response = staff_client.post(
            url,
            {"image": big_file, "alt_text": "Big", "display_order": 0, "is_primary": False},
            format="multipart",
        )
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_list_images_forbidden_for_regular_user(self, regular_client):
        product = ProductFactory(slug="forbidden-img-prod")
        url = reverse("catalog:admin-product-image-list", kwargs={"product_slug": "forbidden-img-prod"})
        response = regular_client.get(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
class TestAdminProductImageDetailView:
    def test_patch_image_alt_text(self, staff_client):
        product = ProductFactory(slug="patch-img-prod")
        img = ProductImage.objects.create(
            product=product, external_url="https://example.com/x.jpg", alt_text="Old"
        )
        url = reverse(
            "catalog:admin-product-image-detail",
            kwargs={"product_slug": "patch-img-prod", "pk": img.pk},
        )
        response = staff_client.patch(url, {"alt_text": "New"}, format="json")
        assert response.status_code == status.HTTP_200_OK
        img.refresh_from_db()
        assert img.alt_text == "New"

    def test_delete_image_hard_delete(self, staff_client):
        product = ProductFactory(slug="hard-del-img-prod")
        img = ProductImage.objects.create(
            product=product, external_url="https://example.com/y.jpg"
        )
        url = reverse(
            "catalog:admin-product-image-detail",
            kwargs={"product_slug": "hard-del-img-prod", "pk": img.pk},
        )
        response = staff_client.delete(url)
        assert response.status_code == status.HTTP_204_NO_CONTENT
        assert not ProductImage.objects.filter(pk=img.pk).exists()

    def test_delete_image_forbidden_for_regular_user(self, regular_client):
        product = ProductFactory(slug="del-img-forbid-prod")
        img = ProductImage.objects.create(
            product=product, external_url="https://example.com/z.jpg"
        )
        url = reverse(
            "catalog:admin-product-image-detail",
            kwargs={"product_slug": "del-img-forbid-prod", "pk": img.pk},
        )
        response = regular_client.delete(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN


# ── Banner Admin Tests ─────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestAdminBannerListView:
    def test_list_banners_staff(self, staff_client):
        Banner.objects.create(
            title="B1", image=SimpleUploadedFile("b1.jpg", b"\xff\xd8\xff", content_type="image/jpeg")
        )
        Banner.objects.create(
            title="B2", image=SimpleUploadedFile("b2.jpg", b"\xff\xd8\xff", content_type="image/jpeg")
        )
        url = reverse("catalog:admin-banner-list")
        response = staff_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        assert response.data["count"] >= 2

    def test_list_banners_forbidden_for_regular_user(self, regular_client):
        url = reverse("catalog:admin-banner-list")
        response = regular_client.get(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN

    def test_create_banner(self, staff_client):
        url = reverse("catalog:admin-banner-list")
        img = SimpleUploadedFile("banner.jpg", _make_jpeg_bytes(), content_type="image/jpeg")
        payload = {
            "title": "New Banner",
            "subtitle": "Sub",
            "eyebrow": "Eyebrow",
            "image": img,
            "cta_text": "Shop now",
            "cta_link": "/products",
            "secondary_cta_text": "Explore",
            "secondary_cta_link": "#categories",
            "display_order": 0,
            "is_active": True,
        }
        response = staff_client.post(url, payload, format="multipart")
        assert response.status_code == status.HTTP_201_CREATED
        assert Banner.objects.filter(title="New Banner").exists()

    def test_create_banner_invalid_image_type(self, staff_client):
        url = reverse("catalog:admin-banner-list")
        gif_file = SimpleUploadedFile("banner.gif", b"GIF89a", content_type="image/gif")
        payload = {
            "title": "Bad Banner",
            "image": gif_file,
            "display_order": 0,
            "is_active": True,
        }
        response = staff_client.post(url, payload, format="multipart")
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_create_banner_image_too_large(self, staff_client):
        url = reverse("catalog:admin-banner-list")
        big_img = SimpleUploadedFile(
            "big_banner.jpg",
            b"\xff\xd8\xff\xe0" + b"\x00" * (11 * 1024 * 1024),
            content_type="image/jpeg",
        )
        payload = {
            "title": "Huge Banner",
            "image": big_img,
            "display_order": 0,
            "is_active": True,
        }
        response = staff_client.post(url, payload, format="multipart")
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    def test_create_banner_forbidden_for_regular_user(self, regular_client):
        url = reverse("catalog:admin-banner-list")
        img = SimpleUploadedFile("b.jpg", b"\xff\xd8\xff", content_type="image/jpeg")
        payload = {"title": "Denied", "image": img, "display_order": 0, "is_active": True}
        response = regular_client.post(url, payload, format="multipart")
        assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
class TestAdminBannerDetailView:
    def _create_banner(self, title="Banner"):
        return Banner.objects.create(
            title=title,
            image=SimpleUploadedFile(f"{title}.jpg", b"\xff\xd8\xff", content_type="image/jpeg"),
        )

    def test_retrieve_banner(self, staff_client):
        banner = self._create_banner("Retrieve Me")
        url = reverse("catalog:admin-banner-detail", kwargs={"pk": banner.pk})
        response = staff_client.get(url)
        assert response.status_code == status.HTTP_200_OK
        assert response.data["title"] == "Retrieve Me"

    def test_update_banner(self, staff_client):
        banner = self._create_banner("Old Title")
        url = reverse("catalog:admin-banner-detail", kwargs={"pk": banner.pk})
        img = SimpleUploadedFile("upd.jpg", _make_jpeg_bytes(), content_type="image/jpeg")
        payload = {
            "title": "New Title",
            "image": img,
            "display_order": 1,
            "is_active": False,
        }
        response = staff_client.put(url, payload, format="multipart")
        assert response.status_code == status.HTTP_200_OK
        banner.refresh_from_db()
        assert banner.title == "New Title"
        assert not banner.is_active

    def test_partial_update_banner(self, staff_client):
        banner = self._create_banner("Partial Banner")
        url = reverse("catalog:admin-banner-detail", kwargs={"pk": banner.pk})
        response = staff_client.patch(url, {"title": "Patched Title"}, format="json")
        assert response.status_code == status.HTTP_200_OK
        banner.refresh_from_db()
        assert banner.title == "Patched Title"

    def test_delete_banner_hard_delete(self, staff_client):
        banner = self._create_banner("Delete Me")
        url = reverse("catalog:admin-banner-detail", kwargs={"pk": banner.pk})
        response = staff_client.delete(url)
        assert response.status_code == status.HTTP_204_NO_CONTENT
        assert not Banner.objects.filter(pk=banner.pk).exists()

    def test_delete_banner_forbidden_for_regular_user(self, regular_client):
        banner = self._create_banner("Protected Banner")
        url = reverse("catalog:admin-banner-detail", kwargs={"pk": banner.pk})
        response = regular_client.delete(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN

    def test_retrieve_banner_forbidden_for_regular_user(self, regular_client):
        banner = self._create_banner("Inaccessible Banner")
        url = reverse("catalog:admin-banner-detail", kwargs={"pk": banner.pk})
        response = regular_client.get(url)
        assert response.status_code == status.HTTP_403_FORBIDDEN
