# Generated by Django 5.2.9 on 2026-08-02 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_unique_non_null_phone_and_more"),
        ("coupons", "0004_remove_coupon_coupon_valid_dates_ordered_and_more"),
        ("orders", "0002_alter_order_idempotency_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_user_idempotency_key",
        ),
        migrations.AddField(
            model_name="order",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_lookup_token",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the order. NULL for guest (anonymous) orders — guest identity is stored in the guest_* fields instead (audit H-4).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["guest_session_id", "status"], name="orders_orde_guest_s_259805_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False), ("user__isnull", False)),
                fields=("user", "idempotency_key"),
                name="unique_user_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("guest_session_id__isnull", False), ("idempotency_key__isnull", False)
                ),
                fields=("guest_session_id", "idempotency_key"),
                name="unique_guest_session_idempotency_key",
            ),
        ),
    ]
