# Generated by Django 5.2.9 on 2026-08-02 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_unique_non_null_phone_and_more"),
        ("coupons", "0004_remove_coupon_coupon_valid_dates_ordered_and_more"),
        ("orders", "0003_remove_order_unique_user_idempotency_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_guest_session_idempotency_key",
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("idempotency_key__isnull", False),
                    models.Q(("guest_session_id", ""), _negated=True),
                ),
                fields=("guest_session_id", "idempotency_key"),
                name="unique_guest_session_idempotency_key",
            ),
        ),
    ]
