# Generated by Django 5.2.9 on 2026-07-18 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("session_key__isnull", False), _connector="OR"
                ),
                name="cart_has_owner",
            ),
        ),
    ]
