# Generated by Django 5.2.9 on 2026-07-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_cart_has_owner"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_has_owner",
        ),
    ]
