# Generated by Django 5.2.9 on 2026-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_productvariant_options_and_more"),
        ("coupons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="coupon_valid_dates_ordered",
            ),
        ),
    ]
