# Generated by Django 5.2.9 on 2026-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_alter_coupon_valid_until_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coupon",
            name="coupon_valid_dates_ordered",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_until",
            field=models.DateTimeField(),
        ),
    ]
