# Generated by Django 5.2.9 on 2026-07-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_idempotency_key_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SUCCEEDED")),
                fields=("order",),
                name="unique_succeeded_payment_per_order",
            ),
        ),
    ]
