# Generated by Django 5.2.9 on 2026-08-02 09:29

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_idempotency_key_and_more"),
        ("payments", "0002_payment_unique_succeeded_payment_per_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual / Cash on Delivery"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("BKASH", "bKash"),
                            ("NAGAD", "Nagad"),
                            ("ROCKET", "Rocket"),
                            ("SSLCOMMERZ", "SSLCommerz"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Step-by-step instructions shown to the customer at checkout.",
                    ),
                ),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("account_name", models.CharField(blank=True, max_length=150)),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.payments.models.payment_method_qr_upload_path,
                    ),
                ),
                (
                    "payment_notes",
                    models.TextField(blank=True, help_text="Extra notes shown with the method."),
                ),
                ("is_sandbox", models.BooleanField(default=True)),
                ("gateway_config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
                "ordering": ["sort_order", "provider"],
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual / Cash on Delivery"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("BKASH", "bKash"),
                    ("NAGAD", "Nagad"),
                    ("ROCKET", "Rocket"),
                    ("SSLCOMMERZ", "SSLCommerz"),
                    ("STRIPE", "Stripe"),
                    ("PAYPAL", "PayPal"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ManualPaymentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_number", models.CharField(max_length=255)),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.payments.models.payment_receipt_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_submissions",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.payment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_payment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="payments.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "manual payment submission",
                "verbose_name_plural": "manual payment submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        default="SUCCEEDED",
                        max_length=20,
                    ),
                ),
                ("refunded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "refund",
                "verbose_name_plural": "refunds",
                "ordering": ["-refunded_at"],
            },
        ),
    ]
