# Generated by Django 5.2.9 on 2026-08-02 10:14

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_seed_payment_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default=apps.payments.models._default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name="refund",
            name="currency",
            field=models.CharField(default=apps.payments.models._default_currency, max_length=3),
        ),
        migrations.CreateModel(
            name="PaymentEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual / Cash on Delivery"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("BKASH", "bKash"),
                            ("NAGAD", "Nagad"),
                            ("ROCKET", "Rocket"),
                            ("SSLCOMMERZ", "SSLCommerz"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=100)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment event log",
                "verbose_name_plural": "payment event logs",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="unique_gateway_event_per_provider"
                    )
                ],
            },
        ),
    ]
