# Generated by Django 5.2.9 on 2026-07-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockmovement_stock_movement_nonzero_delta"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="stock_movement_nonzero_delta",
        ),
    ]
