import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: { xs: '480px', '3xl': '1920px' },
      colors: {
        bg: 'hsl(var(--background) / <alpha-value>)',
        'bg-subtle': 'hsl(var(--background-subtle) / <alpha-value>)',
        background: 'hsl(var(--background) / <alpha-value>)',
        surface: 'hsl(var(--surface) / <alpha-value>)',
        'surface-elevated': 'hsl(var(--surface-elevated) / <alpha-value>)',
        border: 'hsl(var(--border) / <alpha-value>)',
        'border-light': 'hsl(var(--border-light) / <alpha-value>)',
        'border-strong': 'hsl(var(--border-strong) / <alpha-value>)',
        'text-primary': 'hsl(var(--text-primary) / <alpha-value>)',
        'text-secondary': 'hsl(var(--text-secondary) / <alpha-value>)',
        'text-tertiary': 'hsl(var(--text-muted) / <alpha-value>)',
        'text-muted': 'hsl(var(--text-muted) / <alpha-value>)',
        'text-inverse': 'hsl(var(--text-inverse) / <alpha-value>)',
        'text-on-primary': 'hsl(var(--text-on-primary) / <alpha-value>)',
        primary: 'hsl(var(--primary) / <alpha-value>)',
        'primary-hover': 'hsl(var(--primary-hover) / <alpha-value>)',
        'primary-active': 'hsl(var(--primary-active) / <alpha-value>)',
        'primary-light': 'hsl(var(--primary-light) / <alpha-value>)',
        'primary-foreground': 'hsl(var(--primary-foreground) / <alpha-value>)',
        accent: 'hsl(var(--accent) / <alpha-value>)',
        'accent-hover': 'hsl(var(--accent-hover) / <alpha-value>)',
        'accent-subtle': 'hsl(var(--accent-subtle) / <alpha-value>)',
        'accent-foreground': 'hsl(var(--accent-foreground) / <alpha-value>)',
        success: 'hsl(var(--success) / <alpha-value>)',
        'success-subtle': 'hsl(var(--success-subtle) / <alpha-value>)',
        'success-foreground': 'hsl(var(--success-foreground) / <alpha-value>)',
        warning: 'hsl(var(--warning) / <alpha-value>)',
        'warning-subtle': 'hsl(var(--warning-subtle) / <alpha-value>)',
        'warning-foreground': 'hsl(var(--warning-foreground) / <alpha-value>)',
        danger: 'hsl(var(--danger) / <alpha-value>)',
        'danger-subtle': 'hsl(var(--danger-subtle) / <alpha-value>)',
        'danger-foreground': 'hsl(var(--danger-foreground) / <alpha-value>)',
        info: 'hsl(var(--info) / <alpha-value>)',
        'info-subtle': 'hsl(var(--info-subtle) / <alpha-value>)',
        'info-foreground': 'hsl(var(--info-foreground) / <alpha-value>)',
        overlay: 'hsl(var(--overlay) / <alpha-value>)',
        disabled: 'hsl(var(--disabled) / <alpha-value>)',
        'disabled-foreground': 'hsl(var(--disabled-foreground) / <alpha-value>)',
        skeleton: 'hsl(var(--skeleton) / <alpha-value>)',
      },
      fontSize: {
        'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.015em' }],
        'heading-xl': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'heading-lg': ['1.75rem', { lineHeight: '1.25' }],
        'heading-md': ['1.375rem', { lineHeight: '1.3' }],
        'heading-sm': ['1.25rem', { lineHeight: '1.35' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        caption: ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.02em' }],
        overline: ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.08em' }],
        label: ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.01em' }],
      },
      maxWidth: { '8xl': '1440px' },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        'focus-ring': 'var(--shadow-focus-ring)',
      },
      fontFamily: { sans: ['InterVariable', 'Inter', 'system-ui', 'sans-serif'] },
      animation: {
        'fade-in': 'fade-in var(--duration-base) ease-out',
        'slide-in-left': 'slide-in-left var(--duration-slow) cubic-bezier(0.2, 0, 0, 1)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-in-left': { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
      },
    },
  },
  plugins: [],
}

export default config