# Generated by Django 5.2.9 on 2026-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Internal campaign name", max_length=200)),
                ("subject", models.CharField(help_text="Email subject line", max_length=200)),
                (
                    "preview_text",
                    models.CharField(
                        blank=True, help_text="Preview text shown in email clients", max_length=200
                    ),
                ),
                ("html_body", models.TextField(help_text="HTML email body")),
                ("plain_body", models.TextField(blank=True, help_text="Plain-text fallback body")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Newsletter Campaign",
                "verbose_name_plural": "Newsletter Campaigns",
                "ordering": ["-created_at"],
            },
        ),
    ]
