# Generated by Django 5.2.9 on 2026-07-12 12:26

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Small label shown above the title, e.g. 'Exclusive Collection'.",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.catalog.models.banner_image_upload_path),
                ),
                ("cta_text", models.CharField(blank=True, default="Shop now", max_length=50)),
                ("cta_link", models.CharField(blank=True, default="/products", max_length=255)),
                (
                    "secondary_cta_text",
                    models.CharField(blank=True, default="Explore categories", max_length=50),
                ),
                (
                    "secondary_cta_link",
                    models.CharField(blank=True, default="#categories", max_length=255),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="catalog_ban_is_acti_87c034_idx"
                    )
                ],
            },
        ),
    ]
