# Generated by Django 5.2.9 on 2026-07-15 12:02

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=apps.catalog.models.product_image_upload_path
            ),
        ),
    ]
