# Generated by Django 5.2.9 on 2026-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_external_url_to_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gt", 0)), name="product_base_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_at_price__isnull", True), ("compare_at_price__gt", 0), _connector="OR"
                ),
                name="product_compare_price_positive_or_null",
            ),
        ),
    ]
