# Generated by Django 5.2.9 on 2026-07-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_productvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="product_base_price_positive",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="product_compare_price_positive_or_null",
        ),
    ]
