# Generated by Django 5.2.9 on 2026-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationlog_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="recipient",
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
