# Generated by Django 5.2.9 on 2026-07-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification"),
        ("notifications", "0003_alter_notificationlog_recipient"),
    ]

    operations = []
