# Generated by Django 5.2.9 on 2026-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_remove_notificationlog_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ORDER_CONFIRMATION", "Order Confirmation"),
                    ("ORDER_SHIPPED", "Order Shipped"),
                    ("ORDER_DELIVERED", "Order Delivered"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("WELCOME", "Welcome"),
                    ("LOW_STOCK_ALERT", "Low Stock Alert"),
                    ("NEWSLETTER_CONFIRMATION", "Newsletter Confirmation"),
                    ("CONTACT_RECEIVED", "Contact Form Received"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="recipient",
            field=models.EmailField(max_length=254),
        ),
    ]
