# Generated by Django 5.2.9 on 2026-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notificationlog_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ORDER_CONFIRMATION", "Order Confirmation"),
                    ("ORDER_SHIPPED", "Order Shipped"),
                    ("ORDER_DELIVERED", "Order Delivered"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("WELCOME", "Welcome"),
                    ("LOW_STOCK_ALERT", "Low Stock Alert"),
                    ("NEWSLETTER_CONFIRMATION", "Newsletter Confirmation"),
                    ("CONTACT_RECEIVED", "Contact Form Received"),
                    ("PAYMENT_SUBMISSION", "Manual Payment Submission"),
                ],
                max_length=30,
            ),
        ),
    ]
